name: build
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.29.0
      with:
        scan-type: 'fs, repo'
        scan-ref: '.'
        format: json
        exit-code: 1
        severity: CRITICAL,HIGH
